# App Info
ios_app_id                                :                                           # Optional. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
iphone_preview                            : false

playstore_id                              : com.clenet                                # Optional. Enter playstore app id to automatically populate name, price and icons
playstore_link                            : https://play.google.com/store/apps/details?id=com.clenet                                           # Enter Google Play Store URL.

presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/clenet_logo.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : CleNet                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Deliver/Track goods & service,manage & chat.

enable_smart_app_banner                   : false # Set to true to show a smart app banner at top of page on mobile devices.

